name: Deploy docs to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      contents: read
      actions: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Create Pages artifact (include dotfiles)
        run: |
          tar --exclude=.git --exclude=.github -cvf "$RUNNER_TEMP/artifact.tar" -C docs .

      - name: Upload Pages artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ${{ runner.temp }}/artifact.tar
          retention-days: 1

  
  deploy-pages:
    needs: deploy
    runs-on: ubuntu-latest
    permissions:
      pages: write
      contents: read
      id-token: write
      actions: read
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
